<a href="https://colab.research.google.com/github/mameaicha/gomycodeMAC/blob/main/CheckpointNumpy.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

1. Write a Python program to convert an array to an ordinary list with the same items.




In [2]:
import numpy as np

def arrayToList(a):
  """convert an array to an ordinary list """
  r1=a.flatten().tolist() #fonctionne sur une copie du tableau, donc plus rapide et occupe moins de mémoire
  r2=a.ravel().tolist() #renvoie une vue de référence du tableau et affecte le tableau d’origine
  print(r1)
  print(r2)

# oubien
def arrayToList2(a):
  """convert an array to an ordinary list """
  l = []
  for x in a:
    l.append(x)
  print(l)

oned = np.array([[1,2,3]])
twod = np.array([[1,2,3],[4,5,6]])

arrayToList(oned)
arrayToList(twod)

arrayToList2(oned)
arrayToList2(twod)




[1, 2, 3]
[1, 2, 3]
[1, 2, 3, 4, 5, 6]
[1, 2, 3, 4, 5, 6]
[array([1, 2, 3])]
[array([1, 2, 3]), array([4, 5, 6])]


2. Write a NumPy program to compute the sum of the diagonal element of a given array.

In [ ]:
def computDaig(a):
  """compute the sum of the diagonal element of a given array"""
  dim=np.shape(a)
  if a.ndim==1 :
    print("c'est un tableau de dimension 1D donc pas de diagnole")
  else:
     som=0
     for i in range(dim[0]):
        for j in range(dim[1]):
           if (i==j):
              som=som+a[i,j]
     print("la somme des element de la diag est:", som)

twod = np.array([[1,2,3],[4,5,6]])

computDaig(twod)
computDaig(oned)

la somme des element de la diag est: 6
la somme des element de la diag est: 1


3. Given an array of your choice, get all the values higher than X :if a = [[1,2],[3,5]] and x = 2 :  then 3 and 5 are higher than 2.

In [21]:
def subtab(a,x):
  t=a[a>x]
  print(t)
  #oubien
  #dim=np.shape(a)
  #for i in range(dim[0]):
    #for j in range(dim[1]):
      ## Si la valeur est supérieure à X, on l'affiche
      #if (a[i,j] > x):
        #print(a[i,j])

a =np.array ([[1,2],[3,5]]) 
x=2
subtab(a,x)

[3 5]


4. Given two arrays A&B having the same shape. The task is to apply addition of A and B : C is the new array. 

In [22]:
def addition(A,B):
  if np.shape(A)==np.shape(B):
    C=A+B
    print("la somme des deux matrice est:", C)
  else:
    print("les deux tableau n'ont pas les meme dimensions")
  

In [24]:
A = np. array ([[1 , 2 , 3 , 4] , [11 , 12 , 13 , 14] ,
[21 , 22 , 23 , 24] , [31 , 32 , 33 , 34]])

A1 = np. array ([[1 , 2 , 3 , 4] , [11 , 12 , 13 , 14] ,
[21 , 22 , 23 , 24]])


B = np. array ([[1 , 2 , 3 , 4] , [5 , 6 , 7 , 8] ,
[9 , 10 , 11 , 12] , [13 , 14 , 15 , 16]])


addition(A,A1)
addition(A,B)

les deux tableau n'ont pas les meme dimensions
la somme des deux matrice est: [[ 2  4  6  8]
 [16 18 20 22]
 [30 32 34 36]
 [44 46 48 50]]
